services:
  express-todo-api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - NODE_ENV=${NODE_ENV}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET_ACCESS_TOKEN=${JWT_SECRET_ACCESS_TOKEN}
      - JWT_SECRET_REFRESH_TOKEN=${JWT_SECRET_REFRESH_TOKEN}
      - HASH_SECRET=${HASH_SECRET}
      - API_KEY=${API_KEY}
      - MAX_FAILED_ATTEMPTS=${MAX_FAILED_ATTEMPTS}
      - LOCKOUT_DURATION_MINUTES=${LOCKOUT_DURATION_MINUTES}
      - SLIDING_WINDOW_MINUTES=${SLIDING_WINDOW_MINUTES}
      - RATE_LIMIT_WINDOW_MINUTES=${RATE_LIMIT_WINDOW_MINUTES}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
      - TOKEN_REFRESH_LIMIT=${TOKEN_REFRESH_LIMIT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"
    restart: always
